Vb/feat/22/move model generation to sdk
cuba-labs/cuba-front-generator pull request #23
Opened 2019-09-15 18:33 UTC by vadimbasko

contains test-rework #17

2019-09-30 16:02 UTC, web-devel requested changes

2019-09-30 16:02 UTC, web-devel commented on .travis.yml
> +    - name: "Test e2e:react:trusty-dragon"
What does `trusty-dragon` mean ?

2019-09-30 16:02 UTC, web-devel commented on package.json
> +      "src/generators/app/template/**"
Strange path, also react seems to be missing

2019-09-30 16:02 UTC, web-devel commented on src/generators/react-typescript/entity-management/template/EntityManagementBrowser.tsx
> +import {Card, Icon, Modal} from "antd";
We should not delete `List` component import as it's being used in template

2019-09-30 16:02 UTC, web-devel commented on src/generators/sdk/README.md
> +SDK could be generated in different configurations depends on option passed to ```gen-cuba-front``` command.
I suggest:
> It's possible to generate the following configurations of sdk depending on your needs:

2019-09-30 16:02 UTC, web-devel commented on src/generators/sdk/model/model-utils.ts
> +  while (parentClassName && parentPackage && parentClassName.length > 0 && parentPackage.length > 0) {
looks weird )

2019-10-02 11:52 UTC, vadimbasko commented on src/generators/react-typescript/entity-management/template/EntityManagementBrowser.tsx
> +import {Card, Icon, Modal} from "antd";
fixed, conditional import and test will be impleented in #26

2019-10-02 11:53 UTC, vadimbasko commented on src/generators/sdk/README.md
> +SDK could be generated in different configurations depends on option passed to ```gen-cuba-front``` command.
text changed

2019-10-02 11:54 UTC, vadimbasko commented on package.json
> +      "src/generators/app/template/**"
polymer app excluded from coverage - it's ok for now

2019-10-02 12:13 UTC, vadimbasko commented on src/generators/sdk/model/model-utils.ts
> +  while (parentClassName && parentPackage && parentClassName.length > 0 && parentPackage.length > 0) {
fixed

2019-10-02 12:36 UTC, vadimbasko commented on .travis.yml
> +    - name: "Test e2e:react:trusty-dragon"
renamed with new-project

2019-10-02 12:45 UTC, merged